buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
    }
}

rootProject.buildDir = file("../build")
subprojects {
    if (project.projectDir.canonicalPath.startsWith(rootProject.projectDir.canonicalPath + File.separator)) {
        project.buildDir = new File(rootProject.buildDir, project.name)
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
